### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by niallofitz** [lalo-uy/SupervisedFermentor#1]
i've git cloned the repository to my craftbeerpi3/modules/plugins folder. On startup im getting a craftbeerpi3 error saying that there is invalid syntax on line 48 of the __init__.py , please advise

**Comment by lalo-uy** [comment]
There was an extra ) , is ok now.
I hope to commit an updated version tonight.

**Comment by lalo-uy** [comment]
corrected
