### ISSUE TITLE
UPDATE_FERMENTER not correct

### ISSUE THREAD

**Issue by Fuempel** [lalo-uy/SupervisedFermentor#2]
I noticed that the current version is not working for me. Minimum I guess I have to replace

`cbpi.emit("UPDATE_FERMENTER", key)`

by 

`cbpi.emit("UPDATE_FERMENTER", value)`

But not sure, if this is sufficient...

**Comment by lalo-uy** [comment]
Value is the fermenter obj, not its Id

The code is the same as the function toggle in Fermenter class

                t = cbpi.socketio.start_background_task(target=run, instance=instance)
                fermenter.state = not fermenter.state
                cbpi.emit("UPDATE_FERMENTER", cbpi.cache.get(self.cache_key).get(id))

**Comment by lalo-uy** [comment]
You are wright. Thanks
Commited
