### ISSUE TITLE
How To install

### ISSUE THREAD

**Issue by dfcoutinho** [lalo-uy/SupervisedFermentor#3]
Hello.
I did not find this add-on on craftbeerpi3 (System>Add-on ).
Does it work in cbp3.0?
How to install/clone?
Thaks a lot for your attention.

Douglas coutinho

**Comment by lalo-uy** [comment]
Yes it woks.
I have emailed Manuel but got no replay. 
Just clone de repo in craftbeerpi/modules/plugins/ and restart .

**Comment by lalo-uy** [comment]
Timed out
